### ISSUE TITLE
LicenseUrl would be nice to have in dependency.Info

### ISSUE THREAD

**Issue by deschmih** [elastic/go-licence-detector#14]
Feature-Request:
It would be really kind to have the LicenseUrl in the dependency.info for using this information in the templates.

*LicenseFile* is available and also *URL* is available. It is easay to combine this information's to create *LicenseUrl*.

**Comment by charith-elastic** [comment]
`LicenceType` field holds the SPDX identifier of the licence. You can use that to construct the licence URL (e.g. `https://spdx.org/licenses/{{ .LicenceType }}.html`).

**Comment by deschmih** [comment]
Sure, but this works only for SPDX known licenses. Every git-repo should have a license file and the indention was to point out this for documentation if it exists! Instead I got with *LicenseFile* a link to a local file on my drive.

**Comment by charith-elastic** [comment]
If you want to create a hyperlink to the _actual_ licence file on the git repository of the dependency, that is not quite straightforward partly due to vanity URLs and  mainly due to the difficulty of constructing a permalink to the licence file on different git providers (otherwise it could change underneath us). That is why we output the contents of the detected file from the local cache instead: https://github.com/elastic/go-licence-detector/blob/3c2d758256da3d12e383b2d286a47c92e374b85b/example/templates/NOTICE.txt.tmpl#L9

**Comment by deschmih** [comment]
I got the picture and I see the difficulty of construct a permalink. --> I am going to close the feature request. Thx.
